import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BarChart3, Check, ChevronRight, CircleUserRound, Copy, ExternalLink, Link as LinkIcon, LogIn, LogOut, Plus, Radio, ShieldCheck, Sparkles, Users, X, Zap } from 'lucide-react';
import './style.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8080/api';
const api = async (path, opts = {}) => {
  const token = localStorage.getItem('token');
  const res = await fetch(API + path, {
    ...opts,
    headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(opts.headers || {}) }
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error || 'Something went wrong');
  return data;
};

const demoPoll = {
  slug: 'demo', question: 'Which programming language do you prefer?', multiple: false,
  options: [{ id: 'go', text: 'Go', votes: 44 }, { id: 'py', text: 'Python', votes: 28 }, { id: 'js', text: 'JavaScript', votes: 18 }, { id: 'other', text: 'Other', votes: 10 }],
  totalVotes: 156, creatorName: 'Pollify'
};

function Logo({ dark = false }) { return <span className={`logoMark ${dark ? 'dark' : ''}`}><i/><i/><i/></span>; }
function Layout({ children, user, go, logout }) {
  return <div className="appShell"><header className="topbar"><button className="brand" onClick={() => go('home')}><Logo dark/> <span>Pollify</span></button><nav><button onClick={() => go('home')}>Home</button><button onClick={() => go('create')}>Create</button><button onClick={() => go('explore')}>Explore</button></nav><div className="account">{user ? <><span className="avatar">{user.name?.[0]?.toUpperCase()}</span><span className="accountName">{user.name}</span><button className="iconBtn" onClick={logout} title="Sign out"><LogOut size={17}/></button></> : <button className="signin" onClick={() => go('auth')}><LogIn size={16}/> Sign in</button>}</div></header>{children}</div>
}

function Home({ go, user }) {
  return <main>
    <section className="hero"><div className="heroCopy"><div className="eyebrow"><Radio size={14}/> REAL-TIME POLLING</div><h1>Real-time polls for <span>real opinions.</span></h1><p>Create a poll, share one link, and watch every vote arrive instantly. No refresh. No spreadsheet. Just live results.</p><div className="heroActions"><button className="primary" onClick={() => go(user ? 'create' : 'auth')}>Create a Poll <ChevronRight size={18}/></button><button className="ghost" onClick={() => go('explore')}>Explore Polls</button></div><div className="heroMeta"><span><Zap/> Redis-powered live updates</span><span><ShieldCheck/> Secure auth</span><span><Users/> Built for audiences</span></div></div><div className="heroVisual"><PollCard poll={demoPoll} compact/></div></section>
    <section className="section how"><div className="sectionHead"><p className="kicker">THE FLOW</p><h2>From question to live results.</h2></div><div className="steps">{[['01',Plus,'Create Poll','Ask a question and add 2–10 options.'],['02',LinkIcon,'Share Link','Get a unique URL your audience can open.'],['03',Users,'Audience Votes','Anyone with the link can vote once.'],['04',BarChart3,'Live Results','Everyone sees the numbers change live.']].map(([n,Icon,t,d]) => <div className="step" key={n}><div className="stepNum">{n}</div><div className="stepIcon"><Icon/></div><h3>{t}</h3><p>{d}</p></div>)}</div></section>
    <section className="section showcase"><div className="createPreview"><div className="previewHeader"><span>Create a New Poll</span><span className="miniDot">●</span></div><label>Question</label><div className="fakeInput">Which tech stack excites you the most?</div><label>Options</label>{['React','Go','MongoDB','Redis'].map((x,i)=><div className="fakeOption" key={x}><span>Option {i+1}</span><b>{x}</b></div>)}<div className="fakeAdd">＋ Add option</div><div className="toggleLine"><span className="toggle on"><i/></span> Allow multiple votes</div><button className="fakeButton">Create Poll</button></div><div className="resultsPreview"><div className="previewHeader"><span>Live Poll</span><span className="livePill">● LIVE · 42 votes</span></div><h3>Which tech stack excites you the most?</h3>{[['React',38,16],['Go',33,14],['MongoDB',19,8],['Redis',10,4]].map(([x,p,n])=><div className="previewBar" key={x}><div><span>{x}</span><b>{p}%</b></div><div className="track"><i style={{width:`${p}%`}}/></div><small>{n} votes</small></div>)}<div className="sharePreview"><LinkIcon size={16}/> pollify.app/p/abc123 <button>Copy</button></div></div></section>
    <section className="section stack"><div><p className="kicker">TECH STACK</p><h2>Every required layer does real work.</h2><p className="muted">React renders the experience, Go/Gin owns validation and APIs, MongoDB persists state, and Redis powers realtime fan-out.</p></div><div className="stackGrid">{[['React','Frontend'],['Go · Gin','Backend'],['MongoDB','Database'],['Redis','Realtime']].map(([a,b])=><div className="stackCard" key={a}><Sparkles size={20}/><b>{a}</b><span>{b}</span></div>)}</div></section>
  </main>
}

function PollCard({ poll, onVote, compact = false }) {
  const [selected, setSelected] = useState([]); const [voted, setVoted] = useState(false); const [busy, setBusy] = useState(false); const [err, setErr] = useState('');
  const total = poll.totalVotes || poll.options.reduce((s,o)=>s+o.votes,0);
  const choose = id => { if (voted || busy) return; setSelected(prev => poll.multiple ? (prev.includes(id) ? prev.filter(x=>x!==id) : [...prev,id]) : [id]); };
  const submit = async () => { if (!selected.length || !onVote) return; setBusy(true); setErr(''); try { await onVote(selected); setVoted(true); } catch(e) { setErr(e.message); } finally { setBusy(false); } };
  return <div className={`pollCard ${compact ? 'compact' : ''}`}><div className="pollTop"><span className="live"><i/> Live</span><span>{total.toLocaleString()} votes</span></div><h2>{poll.question}</h2>{!compact && <small>Created by {poll.creatorName || 'Pollify'}</small>}<div className="pollOptions">{poll.options.map(o => { const pct = total ? Math.round(o.votes / total * 100) : 0; return <button className={`pollOption ${selected.includes(o.id) ? 'selected' : ''}`} key={o.id} onClick={()=>choose(o.id)}><div className="optionText"><span>{o.text}</span><b>{pct}%</b></div><div className="barTrack"><i style={{width:`${Math.max(pct, 2)}%`}}/></div></button> })}</div>{onVote && <><button className="voteBtn" disabled={!selected.length || voted || busy} onClick={submit}>{busy ? 'Submitting…' : voted ? 'Vote recorded ✓' : poll.multiple ? 'Submit votes' : 'Submit vote'}</button>{err && <div className="inlineError">{err}</div>}</>}</div>
}

function Auth({ done }) { const [mode,setMode]=useState('login'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false); const submit=async e=>{e.preventDefault();setBusy(true);setErr('');try{const d=await api(`/auth/${mode==='login'?'login':'signup'}`,{method:'POST',body:JSON.stringify({name,email,password})});localStorage.setItem('token',d.token);localStorage.setItem('user',JSON.stringify(d.user));done(d.user)}catch(x){setErr(x.message)}finally{setBusy(false)}};return <main className="authPage"><form className="authCard" onSubmit={submit}><Logo/><p className="kicker">POLLIFY ACCOUNT</p><h1>{mode==='login'?'Welcome back.':'Create your account.'}</h1><p className="muted">{mode==='login'?'Sign in to create and manage your polls.':'A lightweight account keeps poll creation private.'}</p>{mode==='signup'&&<input required minLength="2" placeholder="Your name" value={name} onChange={e=>setName(e.target.value)}/>}<input required type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input required minLength="6" type="password" placeholder="Password · 6+ characters" value={password} onChange={e=>setPassword(e.target.value)}/>{err&&<div className="errorBox">{err}</div>}<button className="primary wide" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Sign up'}</button><button type="button" className="textBtn" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'New here? Create an account':'Already have an account? Sign in'}</button></form></main> }

function Create({ go, created }) { const [q,setQ]=useState(''),[opts,setOpts]=useState(['','']),[multiple,setMultiple]=useState(false),[expires,setExpires]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false); const add=()=>opts.length<10&&setOpts([...opts,'']);const submit=async()=>{setBusy(true);setErr('');try{const p=await api('/polls',{method:'POST',body:JSON.stringify({question:q,options:opts,multiple,expiresAt:expires?new Date(expires).toISOString():null})});created(p)}catch(e){setErr(e.message)}finally{setBusy(false)}};return <main className="page"><div className="formCard"><button className="back" onClick={()=>go('home')}>← Home</button><div className="formTitle"><div><p className="kicker">CREATE</p><h1>Ask the room.</h1><p className="muted">Keep it simple. Your audience gets a shareable link as soon as you publish.</p></div><div className="countBadge">{opts.length}/10 options</div></div><label>Question</label><textarea value={q} onChange={e=>setQ(e.target.value)} maxLength={240} placeholder="What should we decide?"/><div className="fieldMeta">{q.length}/240</div><label>Options</label>{opts.map((x,i)=><div className="optionField" key={i}><input value={x} onChange={e=>setOpts(opts.map((v,j)=>j===i?e.target.value:v))} maxLength={100} placeholder={`Option ${i+1}`}/>{opts.length>2&&<button className="iconBtn light" onClick={()=>setOpts(opts.filter((_,j)=>j!==i))}><X size={18}/></button>}</div>)}<button className="addOption" onClick={add} disabled={opts.length>=10}>＋ Add option</button><div className="settings"><label className="checkRow"><input type="checkbox" checked={multiple} onChange={e=>setMultiple(e.target.checked)}/><span><b>Allow multiple choices</b><small>Voters can select more than one option.</small></span></label><label className="expire"><span>End poll (optional)</span><input type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)}/></label></div>{err&&<div className="errorBox">{err}</div>}<button className="primary wide" onClick={submit} disabled={busy}>{busy?'Publishing…':'Create Poll'} <ChevronRight size={18}/></button></div></main> }

function PollPage({ slug, go }) { const [poll,setPoll]=useState(null),[loading,setLoading]=useState(true),[err,setErr]=useState(''); useEffect(()=>{let ws;api(`/polls/${slug}`).then(setPoll).catch(e=>setErr(e.message)).finally(()=>setLoading(false));const wsUrl=API.replace(/^http/,'ws')+`/polls/${slug}/ws`;try{ws=new WebSocket(wsUrl);ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.poll)setPoll(d.poll)}catch{}}}catch{}return()=>ws?.close()},[slug]);const vote=async ids=>{const p=await api(`/polls/${slug}/vote`,{method:'POST',body:JSON.stringify({optionIds:ids})});setPoll(p)};return <main className="pollPage">{loading?<div className="loader">Loading poll…</div>:err?<div className="empty"><h2>Poll not found</h2><p>{err}</p><button className="primary" onClick={()=>go('home')}>Back home</button></div>:<div className="pollShell"><button className="back" onClick={()=>go('home')}>← Pollify</button><div className="pollPageHead"><div><p className="kicker">LIVE POLL</p><h1>Cast your vote.</h1><p className="muted">Results update instantly for everyone watching this poll.</p></div><span className="liveBadge"><i/> LIVE</span></div><PollCard poll={poll} onVote={vote}/><div className="shareBox"><LinkIcon size={18}/><div><b>Share this poll</b><span>{window.location.origin}/p/{slug}</span></div><button onClick={()=>navigator.clipboard?.writeText(window.location.origin+'/p/'+slug)}><Copy size={16}/> Copy</button></div></div>}</main> }

function Explore({ go }) { const [polls,setPolls]=useState([]); useEffect(()=>{api('/polls?limit=12').then(setPolls).catch(()=>{})},[]);return <main className="page"><div className="exploreHead"><div><p className="kicker">DISCOVER</p><h1>Explore live polls.</h1><p className="muted">Open a poll, vote, and watch the results move in real time.</p></div><button className="primary" onClick={()=>go('create')}>Create a Poll <Plus size={18}/></button></div>{polls.length?<div className="pollGrid">{polls.map(p=><button className="pollTile" key={p.slug} onClick={()=>go('poll',p.slug)}><div><span className="livePill"><i/> Live</span><small>{p.totalVotes} votes</small></div><h3>{p.question}</h3><p>{p.options.slice(0,3).map(x=>x.text).join(' · ')}{p.options.length>3?' · …':''}</p><span>Open poll <ChevronRight size={15}/></span></button>)}</div>:<div className="empty"><CircleUserRound size={30}/><h2>No public polls yet.</h2><p>Be the first to create one.</p></div>}</main> }

function App(){const [user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('user'))}catch{return null}});const [route,setRoute]=useState(()=>{const m=location.pathname.match(/^\/p\/([^/]+)/);return m?['poll',m[1]]:['home',null]});const go=(p,arg)=>{setRoute([p,arg||null]);if(p==='poll')history.pushState({},'',`/p/${arg}`);else history.pushState({},'',p==='home'?'/':`/${p}`)};useEffect(()=>{const h=()=>{const m=location.pathname.match(/^\/p\/([^/]+)/);setRoute(m?['poll',m[1]]:[location.pathname.slice(1)||'home',null])};addEventListener('popstate',h);return()=>removeEventListener('popstate',h)},[]);const done=u=>{setUser(u);go('home')};const logout=()=>{localStorage.removeItem('token');localStorage.removeItem('user');setUser(null);go('home')};let [page,arg]=route;let content=page==='home'?<Home go={go} user={user}/>:page==='auth'?<Auth done={done}/>:page==='create'?(user?<Create go={go} created={p=>go('poll',p.slug)}/>:<Auth done={done}/>):page==='explore'?<Explore go={go}/>:page==='poll'?<PollPage slug={arg} go={go}/>:<Home go={go} user={user}/>;return <Layout user={user} go={go} logout={logout}>{content}</Layout>}

createRoot(document.getElementById('root')).render(<App/>);
